#!/bin/sh

#
# A hook script to verify that a push is not done with untracked source file
#
# To use it, either symlink this script to $your-git-clone/.git/hooks/pre-push
# or include it in your existing pre-push script.
#

files=$(git status -u --porcelain --no-column | sed "s/^?? //")
if [ -z "$files" ]; then
  exit 0
fi

echo
echo "ERROR: Preventing push with untracked source files:"
echo
echo "$files" | sed "s/^/    /"
echo
echo "Either include these files in your commits, add them to .gitignore"
echo "or stash them with git stash -u."
echo
exit 1
